name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache android SDK
        uses: actions/cache@v2
        id: android-sdk
        with:
          key: android-sdk
          path: |
            /usr/local/lib/android/adk
            ~/.android
      - name: Setup Android SDK
        if: steps.android-sdk.outputs.cache-hit != 'true'
        uses: android-actions/setup-android@v2
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: |
            flutter doctor -v
            flutter test integration_test --verbose
